# Generated by Django 5.2.17 on 2026-08-21 21:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_transaction_user_id_8af7f1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('asset_type', models.CharField(choices=[('CASH', 'Cash & Liquid Savings'), ('BANK', 'Bank Savings & Deposits'), ('INVESTMENT', 'Stocks, Mutual Funds & ETFs'), ('GOLD', 'Physical & Digital Gold'), ('REAL_ESTATE', 'Real Estate & Property'), ('OTHER', 'Other Assets / Vehicles')], default='BANK', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('institution', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('liability_type', models.CharField(choices=[('CREDIT_CARD', 'Credit Card Outstanding'), ('PERSONAL_LOAN', 'Personal Loan'), ('HOME_LOAN', 'Home / Mortgage Loan'), ('AUTO_LOAN', 'Vehicle / Auto Loan'), ('EDUCATION_LOAN', 'Education Loan'), ('OTHER_DEBT', 'Other Loan / Obligation')], default='PERSONAL_LOAN', max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate_pct', models.DecimalField(decimal_places=2, default=10.5, max_digits=6)),
                ('tenure_months', models.IntegerField(default=24)),
                ('monthly_emi', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('lender', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-remaining_balance'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('BUDGET_WARNING', 'Budget Warning'), ('UNUSUAL_SPENDING', 'Unusual Spending Alert'), ('GOAL_RISK', 'Goal Milestone Risk'), ('UPCOMING_PAYMENT', 'Upcoming Bill Due'), ('FORECAST_WARNING', 'Cash Flow Runaway Alert'), ('DUPLICATE_TRANSACTION', 'Duplicate Charge Detected'), ('INSIGHT_AVAILABLE', 'Smart Financial Insight')], default='INSIGHT_AVAILABLE', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('WARNING', 'Warning Alert'), ('CRITICAL', 'Urgent Action Required')], default='INFO', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(blank=True, default='', max_length=150)),
                ('date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('predicted_category', models.CharField(blank=True, default='Groceries', max_length=100)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0.94, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending User Review'), ('CONFIRMED', 'Confirmed & Transaction Created'), ('REJECTED', 'Rejected by User')], default='PENDING_REVIEW', max_length=20)),
                ('items', models.JSONField(blank=True, default=list)),
                ('raw_ocr_text', models.TextField(blank=True, default='')),
                ('image_url', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_receipt', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
