# Generated by Django 5.2.17 on 2026-08-21 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('AUTH_SUCCESS', 'Authentication Success'), ('AUTH_FAILED', 'Authentication Failure'), ('INJECTION_BLOCKED', 'Hostile Injection Intercepted'), ('BRUTE_FORCE_ATTEMPT', 'Brute Force Attack Detected'), ('TOKEN_ROTATED', 'JWT Token Rotation'), ('SESSION_REVOKED', 'Session Revocation Triggered'), ('VULNERABILITY_SCAN', 'Automated Security Self-Audit'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Anomaly Detected'), ('PROFILE_UPDATED', 'Security Profile Updated'), ('CARD_UNLOCKED', 'Card State Modification')], default='AUTH_SUCCESS', max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('WARNING', 'Warning / Threat Alert'), ('CRITICAL', 'Critical Attack Vector Blocked')], default='INFO', max_length=20)),
                ('source_ip', models.CharField(default='127.0.0.1', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('endpoint', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='security_se_created_723303_idx'), models.Index(fields=['user', '-created_at'], name='security_se_user_id_a067e5_idx'), models.Index(fields=['event_type'], name='security_se_event_t_24a00e_idx'), models.Index(fields=['severity'], name='security_se_severit_3c7077_idx')],
            },
        ),
    ]
