# Generated by Django 5.2.17 on 2026-08-21 23:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('message', models.TextField()),
                ('source_ip', models.CharField(default='127.0.0.1', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='security_co_created_0f5f63_idx'), models.Index(fields=['email'], name='security_co_email_dd86d9_idx'), models.Index(fields=['source_ip', '-created_at'], name='security_co_source__cdf663_idx')],
            },
        ),
    ]
