# Generated by Django 5.2.17 on 2026-08-21 21:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_profile_otp_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='google', max_length=32)),
                ('provider_subject', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('given_name', models.CharField(blank=True, default='', max_length=150)),
                ('family_name', models.CharField(blank=True, default='', max_length=150)),
                ('picture_url', models.URLField(blank=True, default='', max_length=1024)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'provider_subject'], name='authenticat_provide_739c8c_idx'), models.Index(fields=['user', 'provider'], name='authenticat_user_id_7dd362_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_subject'), name='unique_google_provider_subject')],
            },
        ),
    ]
