# Generated by Django 6.1.1 on 2026-09-12 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_profile_avatar_profile_avatar_preset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationsession',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='max_attempts',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='otp_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emaildispatch',
            name='otp_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='verificationsession',
            name='provider',
            field=models.CharField(default='smtp', max_length=32),
        ),
        migrations.AlterField(
            model_name='verificationsession',
            name='purpose',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('LOGIN', 'Login'), ('EMAIL_SIGNUP', 'Email Signup'), ('PASSWORD_RESET', 'Password Reset'), ('EMAIL_CHANGE', 'Email Change'), ('SENSITIVE_ACTION', 'Sensitive Action')], default='REGISTRATION', max_length=32),
        ),
        migrations.AddIndex(
            model_name='verificationsession',
            index=models.Index(fields=['destination', 'purpose', 'status'], name='authenticat_destina_ce1851_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationsession',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_4b028c_idx'),
        ),
    ]
