# Generated by Django 6.1.1 on 2026-09-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_verificationsession_invalidated_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='verificationsession',
            name='authenticat_destina_717ea6_idx',
        ),
        migrations.RemoveIndex(
            model_name='verificationsession',
            name='authenticat_user_id_896684_idx',
        ),
        migrations.RemoveIndex(
            model_name='verificationsession',
            name='authenticat_destina_ce1851_idx',
        ),
        migrations.RemoveIndex(
            model_name='verificationsession',
            name='authenticat_expires_4b028c_idx',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=32),
        ),
        migrations.DeleteModel(
            name='VerificationSession',
        ),
    ]
