/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        /* MONVEX Multi-Family Color Architecture */
        plum: {
          deep: '#2A1F3D',
          rich: '#3B2D54',
          soft: '#625477',
          lavender: '#EEEAF7',
          light: '#F6F3FA',
        },
        indigo: {
          deep: '#26335F',
          medium: '#4056A1',
          soft: '#7184C4',
          tint: '#E9EDFA',
        },
        cyan: {
          bright: '#06B6D4',
          soft: '#DDF7FA',
        },
        tint: {
          lavender: '#EEEAF7',
          plum: '#F6F3FA',
          indigo: '#E9EDFA',
          cyan: '#DDF7FA',
          emerald: '#E8F7F1',
          amber: '#FFF4DF',
          rose: '#FDECEF',
        },
        'dark-surface': {
          brand: '#2A1F3D',
          indigo: '#26335F',
          plum: '#33264A',
          pressed: '#21182F',
        },
        background: 'var(--mx-background)',
        sidebar: 'var(--mx-sidebar)',
        surface: {
          DEFAULT: 'var(--mx-surface)',
          pure: 'var(--mx-surface-pure)',
          subtle: 'var(--mx-surface-subtle)',
          muted: 'var(--mx-surface-muted)',
          raised: 'var(--mx-surface-raised)',
          overlay: 'var(--mx-surface-overlay)',
          50: 'var(--mx-surface-subtle)',
          100: 'var(--mx-surface)',
          200: 'var(--mx-surface-muted)',
          300: 'var(--mx-surface-raised)',
          border: 'var(--mx-border)',
          'border-strong': 'var(--mx-border-strong)',
        },
        text: {
          primary: 'var(--mx-text-primary)',
          secondary: 'var(--mx-text-secondary)',
          muted: 'var(--mx-text-muted)',
          disabled: 'var(--mx-text-disabled)',
        },
        border: {
          DEFAULT: 'var(--mx-border)',
          strong: 'var(--mx-border-strong)',
          interactive: 'var(--mx-border-interactive)',
          'plum-soft': 'var(--mx-border-plum-soft)',
          'indigo-soft': 'var(--mx-border-indigo-soft)',
          'cyan-soft': 'var(--mx-border-cyan-soft)',
        },
        accent: {
          DEFAULT: 'var(--mx-accent)',
          hover: 'var(--mx-accent-hover)',
          active: 'var(--mx-accent-active)',
          soft: 'var(--mx-accent-soft)',
          blue: 'var(--mx-brand-blue)',
          'blue-soft': 'var(--mx-brand-blue-soft)',
        },
        brand: {
          DEFAULT: 'var(--mx-brand-primary)',
          primary: 'var(--mx-brand-primary)',
          hover: 'var(--mx-brand-primary-hover)',
          active: 'var(--mx-brand-primary-active)',
          surface: 'var(--mx-brand-surface)',
          elevated: 'var(--mx-brand-surface-elevated)',
          muted: 'var(--mx-brand-surface-muted)',
          border: 'var(--mx-brand-border)',
          blue: '#2563EB',
          'blue-hover': '#1D4ED8',
        },
        success: {
          DEFAULT: 'var(--mx-success)',
          soft: 'var(--mx-success-soft)',
          border: 'var(--mx-success-border)',
        },
        warning: {
          DEFAULT: 'var(--mx-warning)',
          soft: 'var(--mx-warning-soft)',
          border: 'var(--mx-warning-border)',
        },
        danger: {
          DEFAULT: 'var(--mx-danger)',
          soft: 'var(--mx-danger-soft)',
          border: 'var(--mx-danger-border)',
        },
        cat: {
          food: 'var(--mx-cat-food)',
          'food-text': 'var(--mx-cat-food-text)',
          shop: 'var(--mx-cat-shop)',
          'shop-text': 'var(--mx-cat-shop-text)',
          bills: 'var(--mx-cat-bills)',
          'bills-text': 'var(--mx-cat-bills-text)',
          trans: 'var(--mx-cat-trans)',
          'trans-text': 'var(--mx-cat-trans-text)',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['var(--font-mono)', 'JetBrains Mono', 'Menlo', 'monospace'],
      },
      borderRadius: {
        sm: 'var(--mx-radius-sm)',
        md: 'var(--mx-radius-md)',
        lg: 'var(--mx-radius-lg)',
        xl: 'var(--mx-radius-xl)',
        full: 'var(--mx-radius-full)',
      },
      boxShadow: {
        subtle: 'var(--mx-shadow-subtle)',
        card: 'var(--mx-shadow-card)',
        elevated: 'var(--mx-shadow-elevated)',
        modal: 'var(--mx-shadow-modal)',
      },
    },
  },
  plugins: [],
};
